on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

name: Release Extension
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/setup@v3
        with:
          runtime: node@24
          cache: true
          require-lockfile: true
      - name: Build extension
        run: pnpm run build
      - name: Package extension
        run: pnpm exec vsce package --no-dependencies --out custom-ui-style.vsix
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          extensionFile: custom-ui-style.vsix
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          extensionFile: custom-ui-style.vsix
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
      - run: pnpm dlx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
